import { strict as assert } from 'node:assert';
import { generateGarden, gardenSvg, inchesToMm, isLatestImport, optimizeTravel, parseRecipe, travelDistance, type GardenConfig } from '../lib/plotter.ts';
const base: GardenConfig = { generator: 'herbarium', seed: 77, growth: 62, paper: 'A4', margins: { top: 18, right: 16, bottom: 18, left: 16 }, penLayers: 3, strokeWidth: 0.42 };
for (const generator of ['herbarium', 'orbits', 'lattice'] as const) { const garden = generateGarden({ ...base, generator }); assert.ok(garden.paths.length > 10, `${generator} should produce useful geometry`); garden.paths.flatMap((path) => path.points).forEach((point) => { assert.ok(point.x >= garden.bounds.left && point.x <= garden.bounds.right, `${generator} x escaped margins`); assert.ok(point.y >= garden.bounds.top && point.y <= garden.bounds.bottom, `${generator} y escaped margins`); }); }
assert.equal(inchesToMm(1), 25.4, 'SVG conversion must use the exact 25.4 mm inch');
const garden = generateGarden(base); const optimized = optimizeTravel(garden.paths); assert.equal(new Set(optimized.map((path) => path.id)).size, garden.paths.length, 'optimization must keep every stroke'); const originalGeometry = new Map(garden.paths.map((path) => [path.id, path.d])); optimized.forEach((path) => assert.equal(path.d, originalGeometry.get(path.id), 'optimization must preserve each path segment')); assert.ok(Number.isFinite(travelDistance(optimized)), 'optimized travel is measured');
const svg = gardenSvg(base, garden.paths); assert.match(svg, /width="210mm" height="297mm" viewBox="0 0 210 297"/); assert.match(svg, /data-pen-layer="1"/); assert.match(svg, /<path id="stem-0"/); console.log(`plotter fixtures: ${garden.paths.length} paths, ${travelDistance(garden.paths).toFixed(2)}mm baseline travel`);
const roundTrip = parseRecipe(JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: base, removedIds: ['stem-0'] })); assert.equal(roundTrip?.config.seed, base.seed, 'recipe round trip preserves seed'); assert.deepEqual(roundTrip?.removedIds, ['stem-0'], 'recipe round trip preserves edits'); assert.equal(parseRecipe('{bad json'), null, 'malformed recipe fails cleanly'); assert.equal(parseRecipe(JSON.stringify({ version: 99, kind: 'plotter-garden-recipe', config: base })), null, 'unsupported recipe version fails cleanly');
const invalid = (config: Partial<GardenConfig>) => JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: { ...base, ...config }, removedIds: [] });
assert.equal(parseRecipe(invalid({ margins: { ...base.margins, top: -100 } })), null, 'negative margins are rejected before generation'); assert.equal(parseRecipe(invalid({ growth: 1000000 })), null, 'oversized growth is rejected before generation'); assert.equal(parseRecipe(invalid({ penLayers: 99 })), null, 'oversized layer count is rejected'); assert.equal(parseRecipe(invalid({ strokeWidth: -4 })), null, 'invalid stroke width is rejected'); assert.equal(parseRecipe(JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: { ...base, margins: { top: 18 } }, removedIds: [] })), null, 'partial margins are rejected'); assert.equal(parseRecipe('x'.repeat(512 * 1024 + 1)), null, 'oversized import is rejected before parse');
const bounded = generateGarden({ ...base, growth: 1000000, penLayers: 99, strokeWidth: -4, margins: { top: -100, right: -100, bottom: -100, left: -100 } }); assert.ok(bounded.paths.every((path) => path.points.every((point) => Number.isFinite(point.x) && Number.isFinite(point.y))), 'direct generation caps unsafe values');
const stressBase: GardenConfig = { ...base, seed: 1482, growth: 94, penLayers: 4 }; for (const generator of ['herbarium', 'orbits', 'lattice'] as const) { const full = generateGarden({ ...stressBase, generator }).paths; assert.deepEqual([...new Set(full.map((path) => path.layer))].sort((a, b) => a - b), [0, 1, 2, 3], `${generator} populates all selected pen layers`); const remaining = full.slice(1); const candidate = optimizeTravel(remaining); assert.deepEqual(new Set(candidate.map((path) => path.id)), new Set(remaining.map((path) => path.id)), `${generator} keeps the same removed-path set`); assert.ok(travelDistance(candidate) <= travelDistance(remaining), `${generator} seed 1482 optimizer must not increase travel`); }
assert.equal(isLatestImport(1, 2), false, 'stale import completion is ignored'); assert.equal(isLatestImport(2, 2), true, 'latest import completion is accepted');
