import { strict as assert } from 'node:assert';
import { createImportController, generateGarden, gardenSvg, inchesToMm, isLatestImport, optimizeTravel, parseRecipe, travelDistance, type GardenConfig } from '../lib/plotter.ts';
const base: GardenConfig = { generator: 'herbarium', seed: 77, growth: 62, paper: 'A4', margins: { top: 18, right: 16, bottom: 18, left: 16 }, penLayers: 3, strokeWidth: 0.42 };
for (const generator of ['herbarium', 'orbits', 'lattice'] as const) { const garden = generateGarden({ ...base, generator }); assert.ok(garden.paths.length > 10, `${generator} should produce useful geometry`); garden.paths.flatMap((path) => path.points).forEach((point) => { assert.ok(point.x >= garden.bounds.left && point.x <= garden.bounds.right, `${generator} x escaped margins`); assert.ok(point.y >= garden.bounds.top && point.y <= garden.bounds.bottom, `${generator} y escaped margins`); }); }
assert.equal(inchesToMm(1), 25.4, 'SVG conversion must use the exact 25.4 mm inch');
const garden = generateGarden(base); const optimized = optimizeTravel(garden.paths); assert.equal(new Set(optimized.map((path) => path.id)).size, garden.paths.length, 'optimization must keep every stroke'); const originalGeometry = new Map(garden.paths.map((path) => [path.id, path.d])); optimized.forEach((path) => assert.equal(path.d, originalGeometry.get(path.id), 'optimization must preserve each path segment')); assert.ok(Number.isFinite(travelDistance(optimized)), 'optimized travel is measured');
const svg = gardenSvg(base, garden.paths); assert.match(svg, /width="210mm" height="297mm" viewBox="0 0 210 297"/); assert.match(svg, /data-pen-layer="1"/); assert.match(svg, /<path id="stem-0"/); console.log(`plotter fixtures: ${garden.paths.length} paths, ${travelDistance(garden.paths).toFixed(2)}mm baseline travel`);
const roundTrip = parseRecipe(JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: base, removedIds: ['stem-0'] })); assert.equal(roundTrip?.config.seed, base.seed, 'recipe round trip preserves seed'); assert.deepEqual(roundTrip?.removedIds, ['stem-0'], 'recipe round trip preserves edits'); assert.equal(parseRecipe('{bad json'), null, 'malformed recipe fails cleanly'); assert.equal(parseRecipe(JSON.stringify({ version: 99, kind: 'plotter-garden-recipe', config: base })), null, 'unsupported recipe version fails cleanly');
const invalid = (config: Partial<GardenConfig>) => JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: { ...base, ...config }, removedIds: [] });
assert.equal(parseRecipe(invalid({ margins: { ...base.margins, top: -100 } })), null, 'negative margins are rejected before generation'); assert.equal(parseRecipe(invalid({ growth: 1000000 })), null, 'oversized growth is rejected before generation'); assert.equal(parseRecipe(invalid({ penLayers: 99 })), null, 'oversized layer count is rejected'); assert.equal(parseRecipe(invalid({ strokeWidth: -4 })), null, 'invalid stroke width is rejected'); assert.equal(parseRecipe(JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: { ...base, margins: { top: 18 } }, removedIds: [] })), null, 'partial margins are rejected'); assert.equal(parseRecipe('x'.repeat(512 * 1024 + 1)), null, 'oversized import is rejected before parse');
const bounded = generateGarden({ ...base, growth: 1000000, penLayers: 99, strokeWidth: -4, margins: { top: -100, right: -100, bottom: -100, left: -100 } }); assert.ok(bounded.paths.every((path) => path.points.every((point) => Number.isFinite(point.x) && Number.isFinite(point.y))), 'direct generation caps unsafe values');
const stressBase: GardenConfig = { ...base, seed: 1482, growth: 94, penLayers: 4 }; for (const generator of ['herbarium', 'orbits', 'lattice'] as const) { const full = generateGarden({ ...stressBase, generator }).paths; assert.deepEqual([...new Set(full.map((path) => path.layer))].sort((a, b) => a - b), [0, 1, 2, 3], `${generator} populates all selected pen layers`); const remaining = full.slice(1); const candidate = optimizeTravel(remaining); assert.deepEqual(new Set(candidate.map((path) => path.id)), new Set(remaining.map((path) => path.id)), `${generator} keeps the same removed-path set`); assert.ok(travelDistance(candidate) <= travelDistance(remaining), `${generator} seed 1482 optimizer must not increase travel`); }
assert.equal(isLatestImport(1, 2), false, 'stale import completion is ignored'); assert.equal(isLatestImport(2, 2), true, 'latest import completion is accepted');
const deferred = <T,>() => { let resolve!: (value: T) => void; let reject!: (reason?: unknown) => void; const promise = new Promise<T>((resolvePromise, rejectPromise) => { resolve = resolvePromise; reject = rejectPromise; }); return { promise, resolve, reject }; };
const controller = createImportController(); const controllerState = { seed: 77, removedIds: [] as string[] }; let acceptedImports = 0; let surfacedFailures = 0; let cancelCalls = 0;
const acceptedPayload = deferred<string>(); const acceptedRequest = controller.begin(() => { cancelCalls += 1; }); const acceptedFlow = acceptedPayload.promise.then((text) => { if (!controller.finish(acceptedRequest)) return; const parsed = parseRecipe(text); if (parsed) { controllerState.seed = parsed.config.seed; controllerState.removedIds = parsed.removedIds; acceptedImports += 1; } }); acceptedPayload.resolve(JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: { ...base, seed: 902 }, removedIds: [] })); await acceptedFlow; assert.equal(controllerState.seed, 902, 'current import completion is accepted'); assert.equal(acceptedImports, 1, 'accepted import applies once');
const lateSuccessPayload = deferred<string>(); const lateSuccessRequest = controller.begin(() => { cancelCalls += 1; }); const lateSuccessFlow = lateSuccessPayload.promise.then((text) => { if (!controller.finish(lateSuccessRequest)) return; const parsed = parseRecipe(text); if (parsed) { controllerState.seed = parsed.config.seed; controllerState.removedIds = parsed.removedIds; acceptedImports += 1; } }); controller.invalidate(); controllerState.seed = 1482; controllerState.removedIds.push('stem-99'); lateSuccessPayload.resolve(JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', config: { ...base, seed: 111 }, removedIds: [] })); await lateSuccessFlow; assert.equal(controllerState.seed, 1482, 'late success cannot replace a newer edit'); assert.deepEqual(controllerState.removedIds, ['stem-99'], 'late success cannot restore removed path state'); assert.equal(acceptedImports, 1, 'invalidated success does not apply');
const lateFailurePayload = deferred<string>(); const lateFailureRequest = controller.begin(() => { cancelCalls += 1; }); const lateFailureFlow = lateFailurePayload.promise.catch(() => { if (controller.finish(lateFailureRequest)) surfacedFailures += 1; }); controller.invalidate(); controllerState.removedIds.push('stem-100'); lateFailurePayload.reject(new Error('late read failure')); await lateFailureFlow; assert.deepEqual(controllerState.removedIds, ['stem-99', 'stem-100'], 'late failure keeps newer path edits intact'); assert.equal(surfacedFailures, 0, 'late failure from invalidated import is ignored'); assert.ok(cancelCalls >= 2, 'edit invalidation cancels active readers'); console.log('import controller: accepted completion, edit/remove invalidation, late success and late failure covered');
