'use client';

import { useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, Check, ChevronDown, Download, FileUp, Leaf, MousePointer2, PenLine, RotateCcw, Save, Scissors, Settings2, Sparkles, Undo2, WandSparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { GardenConfig, GeneratorKind, countPoints, gardenSvg, generateGarden, optimizeTravel, paperSize, parseRecipe, travelDistance } from '@/lib/plotter';

const DEFAULT_CONFIG: GardenConfig = { generator: 'herbarium', seed: 1482, growth: 58, paper: 'A4', margins: { top: 18, right: 16, bottom: 18, left: 16 }, penLayers: 3, strokeWidth: 0.42 };
const GENERATORS: Array<{ id: GeneratorKind; label: string; short: string }> = [
  { id: 'herbarium', label: 'Herbarium', short: 'stem + leaf' },
  { id: 'orbits', label: 'Orbitals', short: 'ring + ray' },
  { id: 'lattice', label: 'Lattice bloom', short: 'grid + rosette' },
];
const layerNames = ['Graphite', 'Terracotta', 'Marigold', 'Moss'];
function formatMm(value: number): string { return `${value.toFixed(0)} mm`; }
function downloadFile(filename: string, content: string, type: string) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

export default function Home() {
  const [config, setConfig] = useState<GardenConfig>(DEFAULT_CONFIG);
  const [removedIds, setRemovedIds] = useState<string[]>([]);
  const [history, setHistory] = useState<string[][]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [optimized, setOptimized] = useState(false);
  const [inspect, setInspect] = useState(true);
  const [status, setStatus] = useState('Ready to grow a page.');
  const [savedAt, setSavedAt] = useState<string | null>(null);
  const fileInput = useRef<HTMLInputElement>(null);
  const garden = useMemo(() => generateGarden(config), [config]);
  const orderedPaths = useMemo(() => optimized ? optimizeTravel(garden.paths) : garden.paths, [garden.paths, optimized]);
  const visiblePaths = useMemo(() => orderedPaths.filter((path) => !removedIds.includes(path.id)), [orderedPaths, removedIds]);
  const rawTravel = travelDistance(garden.paths);
  const optimizedTravel = travelDistance(optimizeTravel(garden.paths));
  const travel = travelDistance(visiblePaths);
  const selectedPath = visiblePaths.find((path) => path.id === selectedId) ?? null;
  const paper = paperSize(config.paper);
  const updateConfig = <K extends keyof GardenConfig>(key: K, value: GardenConfig[K]) => { setConfig((current) => ({ ...current, [key]: value })); setRemovedIds([]); setHistory([]); setSelectedId(null); setOptimized(false); };
  const recipe = () => JSON.stringify({ version: 1, kind: 'plotter-garden-recipe', savedAt: new Date().toISOString(), config, removedIds }, null, 2);
  const removeSelected = () => { if (!selectedId) { setStatus('Select a path on the paper first.'); return; } setHistory((current) => [...current, removedIds]); setRemovedIds((current) => [...current, selectedId]); setSelectedId(null); setStatus('Detail removed. Undo is ready if you change your mind.'); };
  const undoRemove = () => { const previous = history.at(-1); if (!previous) { setStatus('Nothing to undo.'); return; } setRemovedIds(previous); setHistory((current) => current.slice(0, -1)); setStatus('Last detail restored.'); };
  const saveRecipe = () => { try { localStorage.setItem('plotter-garden:recipe:v1', recipe()); const now = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); setSavedAt(now); setStatus(`Saved locally at ${now}.`); } catch { setStatus('Local storage is blocked or full. Use Export recipe instead.'); } };
  const reopenRecipe = () => { try { const stored = localStorage.getItem('plotter-garden:recipe:v1'); if (!stored) { setStatus('No local recipe yet. Save this drawing first.'); return; } const parsed = parseRecipe(stored); if (!parsed) throw new Error('unsupported'); setConfig(parsed.config); setRemovedIds(parsed.removedIds); setHistory([]); setSelectedId(null); setOptimized(false); setSavedAt(parsed.savedAt ? new Date(parsed.savedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : null); setStatus('Reopened the saved recipe.'); } catch { setStatus('That local recipe could not be reopened. Export a fresh copy to recover.'); } };
  const exportRecipe = () => downloadFile('plotter-garden-recipe.json', recipe(), 'application/json');
  const exportSvg = () => { downloadFile(`plotter-garden-${config.generator}-${config.seed}.svg`, gardenSvg(config, visiblePaths), 'image/svg+xml'); setStatus(`Exported ${visiblePaths.length} paths as scaled SVG.`); };
  const importRecipe = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (file.size > 512 * 1024) { setStatus('Import rejected: recipe is over the 512 KB safety limit.'); return; } const reader = new FileReader(); reader.onload = () => { const text = typeof reader.result === 'string' ? reader.result : ''; const parsed = parseRecipe(text); if (!parsed) { setStatus('Import failed: unsupported recipe or malformed JSON.'); return; } setConfig({ ...DEFAULT_CONFIG, ...parsed.config, margins: { ...DEFAULT_CONFIG.margins, ...parsed.config.margins } }); setRemovedIds(parsed.removedIds); setHistory([]); setSelectedId(null); setOptimized(false); setStatus('Imported recipe. The garden is ready to edit.'); }; reader.onerror = () => setStatus('Import failed: the file could not be read.'); reader.readAsText(file); };
  return <main className="app-shell">
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark"><Leaf size={17} strokeWidth={2.2} /></div><div><p className="eyebrow">Studio 04 / local instrument</p><p className="brand-name">Plotter <span>Garden</span></p></div></div><div className="top-actions"><span className="local-pill"><span className="live-dot" /> runs in your browser</span><Button variant="ghost" size="sm" onClick={saveRecipe}><Save size={14} /> Save</Button><Button variant="outline" size="sm" onClick={exportSvg}><Download size={14} /> Export SVG</Button></div></header>
    <div className="workspace">
      <aside className="control-rail"><div className="rail-heading"><div><p className="eyebrow">01 / choose a species</p><h1>Grow a drawing</h1></div><Sparkles size={18} className="heading-icon" /></div>
        <section className="generator-list" aria-label="Generator choices">{GENERATORS.map((generator) => <button key={generator.id} className={`generator-card ${config.generator === generator.id ? 'is-active' : ''}`} onClick={() => updateConfig('generator', generator.id)}><span className={`generator-glyph glyph-${generator.id}`} aria-hidden="true">{generator.id === 'herbarium' ? '⌁' : generator.id === 'orbits' ? '◎' : '✣'}</span><span><strong>{generator.label}</strong><small>{generator.short}</small></span>{config.generator === generator.id && <Check size={16} className="check-icon" />}</button>)}</section>
        <section className="controls-section"><div className="section-label"><span>02 / tune the growth</span><Settings2 size={14} /></div><label className="field-label" htmlFor="seed">Seed <span className="value-chip">{config.seed}</span></label><input id="seed" className="text-input" type="number" min="0" max="999999" value={config.seed} onChange={(event) => updateConfig('seed', Math.max(0, Number(event.target.value) || 0))} /><label className="field-label" htmlFor="growth">Growth <span className="value-chip">{config.growth}%</span></label><input id="growth" className="range-input" type="range" min="10" max="94" value={config.growth} onChange={(event) => updateConfig('growth', Number(event.target.value))} /><div className="range-hint"><span>whisper</span><span>thicket</span></div><label className="field-label" htmlFor="stroke">Pen weight <span className="value-chip">{config.strokeWidth.toFixed(2)} mm</span></label><input id="stroke" className="range-input" type="range" min="0.18" max="0.9" step="0.01" value={config.strokeWidth} onChange={(event) => updateConfig('strokeWidth', Number(event.target.value))} /></section>
        <section className="controls-section paper-section"><div className="section-label"><span>03 / choose paper</span><PenLine size={14} /></div><label className="field-label" htmlFor="paper">Paper size</label><div className="select-wrap"><select id="paper" className="text-input select-input" value={config.paper} onChange={(event) => updateConfig('paper', event.target.value as GardenConfig['paper'])}><option>A4</option><option>A3</option><option>Letter</option></select><ChevronDown size={15} /></div><div className="paper-meta"><span>{paper.width} × {paper.height} mm</span><span>portrait</span></div><label className="field-label" htmlFor="margins">Safe margin <span className="value-chip">{config.margins.left} mm</span></label><input id="margins" className="range-input" type="range" min="8" max="35" value={config.margins.left} onChange={(event) => { const value = Number(event.target.value); updateConfig('margins', { top: value, right: value, bottom: value, left: value }); }} /><div className="margin-note">Same inset on all sides · paths stay inside</div></section>
        <section className="quick-actions"><div className="section-label"><span>04 / make it yours</span><MousePointer2 size={14} /></div><div className="action-row"><Button variant="outline" size="sm" onClick={removeSelected}><Scissors size={14} /> Remove detail</Button><Button variant="ghost" size="sm" onClick={undoRemove} disabled={!history.length}><Undo2 size={14} /> Undo</Button></div><label className="toggle-row"><input type="checkbox" checked={inspect} onChange={(event) => setInspect(event.target.checked)} /><span className="toggle-box" /> Inspect paths <span className="toggle-help">click a line</span></label></section>
        <div className="rail-footer"><span>Tip</span><p>Every seed is a recipe. Save one, then change the growth to make a family.</p></div>
      </aside>
      <section className="canvas-column"><div className="canvas-header"><div><p className="eyebrow">{GENERATORS.find((item) => item.id === config.generator)?.label} / live preview</p><h2>garden-{config.generator}-{config.seed}</h2></div><Badge variant="outline"><span className="badge-dot" /> {visiblePaths.length} paths</Badge></div><div className="paper-stage"><div className="stage-note top-left">PAPER / {config.paper}</div><div className="stage-note top-right">{formatMm(paper.width)} × {formatMm(paper.height)}</div><div className="paper-shadow"><svg className="garden-svg" viewBox={`0 0 ${paper.width} ${paper.height}`} aria-label={`${config.generator} drawing preview on ${config.paper} paper`}><rect width={paper.width} height={paper.height} fill="#f8f1e5" /><defs><pattern id="paper-grain" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="3" cy="6" r="0.35" fill="#7b6d5a" opacity="0.12" /><circle cx="15" cy="16" r="0.28" fill="#7b6d5a" opacity="0.1" /></pattern></defs><rect width={paper.width} height={paper.height} fill="url(#paper-grain)" /><rect x={config.margins.left} y={config.margins.top} width={paper.width - config.margins.left - config.margins.right} height={paper.height - config.margins.top - config.margins.bottom} fill="none" stroke="#bda98b" strokeDasharray="1.8 2.5" strokeWidth="0.42" opacity="0.72" />{visiblePaths.map((path) => <path key={path.id} d={path.d} data-path-id={path.id} className={`draw-path ${selectedId === path.id ? 'is-selected' : ''}`} stroke={path.color} strokeWidth={config.strokeWidth} fill="none" onClick={() => inspect && setSelectedId(path.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setSelectedId(path.id); }} tabIndex={inspect ? 0 : -1} role={inspect ? 'button' : undefined} aria-label={inspect ? `Select ${path.id}` : undefined} />)}{inspect && selectedPath && <><circle cx={selectedPath.start.x} cy={selectedPath.start.y} r="1.4" fill="#cf5a3d" /><circle cx={selectedPath.end.x} cy={selectedPath.end.y} r="1.4" fill="#cf5a3d" /></>}</svg></div><div className="stage-note bottom-left">{inspect ? 'CLICK A LINE TO INSPECT' : 'INSPECTION OFF'}</div><div className="stage-note bottom-right">{optimized ? 'ORDER / OPTIMIZED' : 'ORDER / ORIGINAL'}</div></div><div className="canvas-caption"><span><span className="caption-mark" /> margin-safe preview</span><span>Paper geometry is measured in millimetres · export stays vector</span></div></section>
      <aside className="inspector-rail"><div className="inspector-heading"><div><p className="eyebrow">Path desk</p><h2>Make the pen travel less.</h2></div><WandSparkles size={18} className="heading-icon" /></div><p className="inspector-copy">Reorder whole strokes to reduce lift-and-travel distance. The drawn geometry never changes.</p><div className="metric-card"><div className="metric-top"><span>Travel distance</span><Badge variant="secondary">heuristic</Badge></div><div className="metric-values"><div><strong>{travel.toFixed(0)}</strong><span>mm current</span></div><div className="metric-arrow">→</div><div className="metric-after"><strong>{(optimized ? travel : optimizedTravel).toFixed(0)}</strong><span>mm after order</span></div></div><div className="meter"><span style={{ width: `${Math.max(14, Math.min(100, rawTravel ? ((optimized ? travel : optimizedTravel) / rawTravel) * 100 : 0))}%` }} /></div><div className="metric-foot"><span>{rawTravel > optimizedTravel ? `${((1 - optimizedTravel / rawTravel) * 100).toFixed(0)}% less lift travel` : 'Already in a tidy order'}</span><span>measured</span></div></div><Button className="optimize-button" onClick={() => { setOptimized(true); setStatus('Travel order optimized. Geometry preserved stroke-for-stroke.'); }}><ArrowDownToLine size={15} /> Optimize travel</Button><div className="honest-note"><span className="note-symbol">i</span><p><strong>Bounded heuristic.</strong> Nearest-neighbour ordering is fast and useful, but not a guarantee of the global shortest route.</p></div>
        <section className="inspect-card"><div className="card-heading"><span>Selected path</span><span className="tiny-status">{selectedPath ? 'ACTIVE' : 'NONE'}</span></div>{selectedPath ? <><h3>{selectedPath.id}</h3><div className="path-detail-grid"><span>layer <b>{selectedPath.layer + 1}</b></span><span>points <b>{selectedPath.points.length}</b></span><span>start <b>{selectedPath.start.x.toFixed(1)}, {selectedPath.start.y.toFixed(1)}</b></span><span>end <b>{selectedPath.end.x.toFixed(1)}, {selectedPath.end.y.toFixed(1)}</b></span></div><Button variant="destructive" size="sm" onClick={removeSelected}><Scissors size={13} /> Remove this detail</Button></> : <div className="empty-inspect"><MousePointer2 size={17} /><span>Turn inspection on, then click any line in the paper.</span></div>}</section>
        <section className="layers-card"><div className="card-heading"><span>Pen layers</span><span className="tiny-status">{config.penLayers} ACTIVE</span></div>{Array.from({ length: config.penLayers }, (_, index) => <div className="layer-row" key={index}><span className="layer-swatch" style={{ backgroundColor: `var(--ink-${index + 1})` }} /><span>{layerNames[index]}</span><span className="layer-count">{visiblePaths.filter((path) => path.layer === index).length}</span></div>)}<label className="field-label layers-field" htmlFor="layers">Layer count <span className="value-chip">{config.penLayers}</span></label><input id="layers" className="range-input" type="range" min="1" max="4" value={config.penLayers} onChange={(event) => updateConfig('penLayers', Number(event.target.value))} /></section>
        <section className="file-card"><div className="card-heading"><span>Recipe / v1</span><span className="tiny-status">LOCAL</span></div><p>Save the seed, rules, paper and edits as a portable recipe.</p><div className="file-actions"><Button variant="outline" size="sm" onClick={saveRecipe}><Save size={13} /> Save</Button><Button variant="ghost" size="sm" onClick={reopenRecipe}><RotateCcw size={13} /> Reopen</Button></div><div className="file-actions"><Button variant="outline" size="sm" onClick={exportRecipe}><Download size={13} /> Export recipe</Button><Button variant="ghost" size="sm" onClick={() => fileInput.current?.click()}><FileUp size={13} /> Import</Button><input ref={fileInput} type="file" accept="application/json,.json" className="visually-hidden" onChange={importRecipe} /></div>{savedAt && <span className="saved-line"><Check size={12} /> last local save {savedAt}</span>}</section><output className="status-line"><span className="status-dot" /> {status}</output>
      </aside>
    </div><footer className="bottom-bar"><span><span className="footer-emblem">✳</span> Plotter Garden</span><span>{countPoints(visiblePaths).toLocaleString()} points · {formatMm(travel)} pen travel · no upload</span><span>v1.0 / local-first</span></footer>
  </main>;
}
